In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import math 

from sklearn.feature_extraction import DictVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from numpy import random

In [6]:
#by using sklearn.feature_extraction import DictVectorizer, we can atract information that we needs! 
data = [
    {'city': 'New York', 'temperature': 21, 'humidity': 68},
    {'city': 'Los Angeles', 'temperature': 25, 'humidity': 75},
    {'city': 'Chicago', 'temperature': 14, 'humidity': 85},
    {'city': 'San Francisco', 'temperature': 18, 'humidity': 80}
]

# Bước 2: Khởi tạo DictVectorizer
vec = DictVectorizer(sparse=False)

# Bước 3: Chuyển đổi dữ liệu từ điển sang ma trận
X = vec.fit_transform(data)

# Bước 4: Chia tập dữ liệu thành tập huấn luyện và tập kiểm tra
X_train, X_test = train_test_split(X, test_size=0.25, random_state=42)

# Bước 5: Chuẩn hóa dữ liệu
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# In ra các đặc tính đã được biến đổi và dữ liệu đã được chuẩn hóa
print("Các đặc tính:", vec.get_feature_names_out())
print("Dữ liệu sau khi biến đổi:\n", X)
print("Dữ liệu huấn luyện đã chuẩn hóa:\n", X_train_scaled)
print("Dữ liệu kiểm tra đã chuẩn hóa:\n", X_test_scaled)

Các đặc tính: ['city=Chicago' 'city=Los Angeles' 'city=New York' 'city=San Francisco'
 'humidity' 'temperature']
Dữ liệu sau khi biến đổi:
 [[ 0.  0.  1.  0. 68. 21.]
 [ 0.  1.  0.  0. 75. 25.]
 [ 1.  0.  0.  0. 85. 14.]
 [ 0.  0.  0.  1. 80. 18.]]
Dữ liệu huấn luyện đã chuẩn hóa:
 [[-0.70710678  0.         -0.70710678  1.41421356  0.32708852  0.11624764]
 [-0.70710678  0.          1.41421356 -0.70710678 -1.35508101  1.16247639]
 [ 1.41421356  0.         -0.70710678 -0.70710678  1.02799249 -1.27872403]]
Dữ liệu kiểm tra đã chuẩn hóa:
 [[-0.70710678  1.         -0.70710678 -0.70710678 -0.37381545  2.55744805]]


In [9]:
#Neutral Network from scratch, we only make the sigmoid function, the other can be contruct as well, such as ReLU
#We base on cross_entropy lost function, this will ensure maybe the best results we can have 

class Neutral_Network: 
    def __init__(self, expoch = 100, layers = [1,3,1]):  
        self.expoch = expoch 
        self.layers = layers  
        #first intialize! 
        self.W = [np.random.normal(loc = 0, scale = 0.01, size = (layers[x], layers[x+1])) for x in range(0,len(layers)-1)]
        self.B = [np.random.normal(loc = 0, scale = 0.01, size = (1,layers[x])) for x in range(0,len(layers)-1)]

    def sigmoid(self,x):
        return 1 / (1 + np.exp(-x))  
    
    def d_sigmoid(self,x):
        #derivative of sigmoid function (this can be proof!) 
        return x * (1-x) 

    def fit(self,x,y): 

        #Forward Technique (as a child, we have to run Native using A[T] = X*W.T + b, for T is the Layer we are using)
        #Note that, A[0] = X, A[len(layers) - 1] = Y!, W[layer] = W between layer and layer + 1, the same for B 
        A = [x] 
        
        #we come for forward technique, that is running straight 
        for layer in range(0,len(self.layers) - 1): 
            A.append(self.sigmoid(np.dot(A[-1],self.W[layer]) + self.B[layer])) 

        #after ther forward, we will back_track to find the best result! 
        #Step 1: find dL/dA[-1] -> step 2: find dL/dw and dL / db, step 3: return to step 1

        da = [(-y/A[-1]) + (1-y)/(1-A[-1])] #step 1 done!
        dw = [] #this stand for dL / dw[T], for T is the layer ! 
        db = [] 
    
        for layer in reversed(range(0,len(self.layers) - 1)): 
            #dL/dw = dL/dA[T] * dA[T]/dz[T] * dz... 
            dw.append(np.dot((A[layer-1]).T, self.d_sigmoid(A[layer]) * da[-1])) 
            db.append() 
            da.append()

        
        

[array([[0.0013551 , 0.0026405 , 0.00199675]]), array([[ 0.00282631],
       [-0.00587861],
       [ 0.00450246]])]


In [ ]:
A = Neutral_Network()  
A.fit([1,2],[3,4])